const Products = [
  {
    category: 'House',
    price: '638000',
    stocked: true,
    name: 'A',
    location: '575 Canterbury Rd, Campsie NSW 2194',
    house: true,
    bed: '1',
  },
  {
    category: 'Apartment & Units',
    price: '520000',
    stocked: true,
    name: 'B',
    location: '301 Sandy Bay Rd, Sandy Bay TAS 7005',
    apartment: true,
    bed: '2',
  },
  {
    category: 'TownHouse',
    price: '472000',
    stocked: false,
    name: 'C',
    location: '349 Barkers Rd, Kew VIC 3101',
    townhouse: true,
    bed: '3',
  },
  {
    category: 'Villa',
    price: '936000',
    stocked: true,
    name: 'D',
    location: 'Shop 2/40 Elizabeth St, Hobart TAS 7000',
    villa: true,
    bed: '4',
  },
  {
    category: 'Land',
    price: '882000',
    stocked: false,
    name: 'E',
    location: '17/5 Opal Dr, Blackmans Bay TAS 7052',
    land: true,
    bed: '5',
  },
  {
    category: 'Acreage',
    price: '1123000',
    stocked: true,
    name: 'F',
    location: '65 Bellevue Parade, New Town TAS 7008',
    acreage: true,
    bed: '6',
  },
  {
    category: 'Rural',
    price: '493000',
    stocked: true,
    name: 'G',
    location: '365 Turbot St, Spring Hill QLD 4000',
    rural: true,
    bed: '1',
  },
  {
    category: 'Block of Units',
    price: '533000',
    stocked: true,
    name: 'H',
    location: '218 Warrigal Rd, Runcorn QLD 4113',
    block: true,
    bed: '2',
  },
  {
    category: 'Retirement Living',
    price: '628000',
    stocked: true,
    name: 'I',
    location: '59 Nerang St, Southport QLD 4215',
    retirement: true,
    bed: '3',
  },
];

export default Products;
